Feature: #19 feed service 및 controller 구현
CAFREE-dev/cafree-backend pull request #22
Opened 2022-12-02 06:43 UTC by lcomment

## 개요

> Feed 관련 Service와 Controller 구현
> Feed 관련 crud api 구현

## 작업사항

- 엔티티 컬럼 추가
  - 피드 -> 좋아요
  - 이미지 -> 순서
- 컬럼 추가에 따른 Repository 코드 수정
- Service 및 Controller 구현

## 변경로직

**prev**
```java
생략
```

**changed**
```java
생략
```

## 기타

- 테스트 작성 진행중
- 엔티티 컬럼 관련 논의 지속적으로 필요

2022-12-02 12:55 UTC, rt3310 requested changes
한 번 메서드 좀 더 분리하면서 작성해보면 좋을 것 같아 good

2022-12-02 12:55 UTC, rt3310 commented on src/main/java/net/cafree/domain/feed/dto/request/FeedAddRequest.java
> +                             Integer likes,
likes가 어떤 의미로 썼었지

2022-12-02 12:55 UTC, rt3310 commented on src/main/java/net/cafree/domain/feed/dto/request/FeedAddRequest.java
> -                             Double likePoint,
생각해보니까 그 피드에서 카페 점수(ex 2.5)주는 것 때문에 필드에 넣었는데 이부분 왜 뺐었지

2022-12-02 12:55 UTC, rt3310 commented on src/main/java/net/cafree/domain/feed/repository/FeedImageRepository.java
> +    List<FeedImage> findByFeed_Id(Long feedId);
여기 언더바 안들어가면 인식 못하나?

2022-12-02 12:55 UTC, rt3310 commented on src/main/java/net/cafree/domain/feed/service/FeedTagService.java
> +        return feedTagRepository.saveAll(feedTags);
이렇게 바꿀 수 있을 것 같아

```java
return feedTagRepository.saveAll(tags.stream()
                .map(tag -> new FeedTag(tag, feed))
                .collect(Collectors.toList()));
```

2022-12-02 12:55 UTC, rt3310 commented on src/main/java/net/cafree/domain/feed/service/TagService.java
> +        return tags;
이 로직을 이렇게 메서드 분리시켜서 작성해보면 좋을 것 같아
findByTagName을 Optional로 받으면 orElseGet 문으로 간결하게 쓸 수 있어
그리고 else문은 지양하는게 좋은데 분리시키면 else문을 사용하지 않고 해결할 수 있어

```java
@Transactional
public List<Tag> saveAll(FeedAddRequest feedAddRequest) {
    return feedAddRequest.tags().stream()
            .map(this::getSavedTag)
            .collect(Collectors.toList());
}

private Tag getSavedTag(String tagName) {
    return findByTagName(tagName)
            .orElseGet(() -> tagRepository.save(new Tag(tagName)));
}
```

2022-12-03 03:15 UTC, lcomment commented on src/main/java/net/cafree/domain/feed/controller/FeedController.java
> +                        .collect(Collectors.toList())));
컨트롤러에서 메서드 분리할 생각을 못했네 분리해볼게~

2022-12-03 03:17 UTC, lcomment commented on src/main/java/net/cafree/domain/feed/dto/request/FeedAddRequest.java
> +                             Integer likes,
likes는 피드 좋아요 넣은건데 지금 확인해보니까 설계할 때 아예 테이블로 뺏구나 수정할게

2022-12-03 03:17 UTC, lcomment commented on src/main/java/net/cafree/domain/feed/dto/request/FeedAddRequest.java
> -                             Double likePoint,
카페 점수인지 몰랐음 `likes` 빼고 `likePoint` 다시 넣을게

2022-12-03 03:18 UTC, lcomment commented on src/main/java/net/cafree/domain/feed/repository/FeedImageRepository.java
> +    List<FeedImage> findByFeed_Id(Long feedId);
해본적은 없는데 한번 해보고 수정하거나 그대로 두거나 할게

2022-12-03 03:25 UTC, rt3310 commented on src/main/java/net/cafree/domain/feed/controller/FeedController.java
> +                        .collect(Collectors.toList())));
아니면 저 get메서드를 엔티티 내부에 써보는 것도 괜찮은가??

2022-12-03 03:25 UTC, rt3310 commented on src/main/java/net/cafree/domain/feed/controller/FeedController.java
> +                        .collect(Collectors.toList())));
위치상 보면 엔티티 내부가 더 잘어울리는거 같긴한데

2022-12-03 03:39 UTC, lcomment commented on src/main/java/net/cafree/domain/feed/controller/FeedController.java
> +                        .collect(Collectors.toList())));
슬랙에 메세지 남김

2022-12-03 03:53 UTC, lcomment commented on src/main/java/net/cafree/domain/feed/repository/FeedImageRepository.java
> +    List<FeedImage> findByFeed_Id(Long feedId);
언더바 빼고 빌드 문제 없는거 보니까 상관없어보이네 언더바 뺄게~

2022-12-03 03:58 UTC, lcomment commented on src/main/java/net/cafree/domain/feed/service/TagService.java
> +        return tags;
어떻게 분리하지 고민하다가 if-else문 그냥 박았는데 ㅋㅋㅋ 굳굳

2022-12-03 07:03 UTC, rt3310 approved these changes
great

2022-12-03 07:03 UTC, rt3310 commented on src/main/java/net/cafree/domain/feed/dto/response/FeedResponse.java
> +                           Double likeCount,
이거 위에 likePoint 의미하는건가?

2022-12-03 07:08 UTC, lcomment commented on src/main/java/net/cafree/domain/feed/dto/response/FeedResponse.java
> +                           Double likeCount,
웅 likePoint였구나? count인줄

2022-12-03 07:11 UTC, lcomment commented on src/main/java/net/cafree/domain/feed/dto/request/FeedAddRequest.java
> -                             Double likePoint,
테이블을 따로 분리해서 상관없을거 같은데?

2022-12-03 07:13 UTC, rt3310 commented on src/main/java/net/cafree/domain/feed/dto/request/FeedAddRequest.java
> -                             Double likePoint,
일단 ㅇㅋ

2022-12-03 07:14 UTC, lcomment commented on src/main/java/net/cafree/domain/feed/dto/request/FeedAddRequest.java
> -                             Double likePoint,
Count만 Point로 다시 원복할게 일단

2022-12-03 10:04 UTC, rt3310 approved these changes
response에 likeCount만 추가해주면 문제없을거같아

2022-12-03 10:04 UTC, rt3310 commented on src/main/java/net/cafree/domain/feed/dto/response/FeedResponse.java
> -                           Long likeCount,
생각해보니까 우리 request엔 likeCount 없어도 되는데 response에는 있어야 할듯?

2022-12-03 10:06 UTC, lcomment commented on src/main/java/net/cafree/domain/feed/dto/response/FeedResponse.java
> -                           Long likeCount,
이거는 피드 좋아요 테이블 만들면서 추가하는거 어때?

2022-12-03 10:08 UTC, rt3310 commented on src/main/java/net/cafree/domain/feed/dto/response/FeedResponse.java
> -                           Long likeCount,
ㅇㅋ good

2022-12-03 10:08 UTC, merged