Feature/#28
CAFREE-dev/cafree-backend pull request #34
Opened 2023-02-03 07:43 UTC by rt3310

## 개요
구글 security oauth2 login 구현

## 작업사항

SecurityConfig에 oauth2Login 추가
oauth2 구글 처리 로직 구현
CustomUserDetails에 OAuth2User인터페이스 추가 
CustomUserDetails - > LoginUser 메서드명 변경
CustomUserDetailsServcice - > LoginUserDetailsService 메서드명 변경

## 변경로직

**prev**
```java
생략
```

**changed**
```java
생략
```

## 기타

LoginUserDetailsService는 삭제해도 무방할 것으로 보임

2023-02-04 02:16 UTC, lcomment requested changes
확인했어~ 혹시 oauth 과정 너가 짤 클래스로 flow 간단하게 설명 가능?

2023-02-04 02:16 UTC, lcomment commented on src/main/java/net/cafree/security/jwt/JwtAuthenticationFilter.java
> +    private final LoginUserDetailsService customUserDetailsService;
클래명 변경해서 객체명도 바꿔야할거 같아

2023-02-04 02:16 UTC, lcomment commented on src/main/java/net/cafree/security/jwt/JwtTokenProvider.java
> +    private String generateToken(String id, String nickname, long expireTime) {
나도 이거 고민하다가 Long 타입 줬는데, 결국 String으로 바꼈구나 ㅋㅋ

2023-02-05 14:05 UTC, rt3310 commented on src/main/java/net/cafree/security/jwt/JwtAuthenticationFilter.java
> +    private final LoginUserDetailsService customUserDetailsService;
아 ㅇㅋㅇㅋ

2023-02-05 14:06 UTC, rt3310 commented on src/main/java/net/cafree/security/jwt/JwtTokenProvider.java
> +    private String generateToken(String id, String nickname, long expireTime) {
ㅋㅋㅋㅋㅋ 엉 일단 바꾸긴했는데 네이밍도 바꿀까 고민중

2023-02-05 14:06 UTC, rt3310 commented on src/main/java/net/cafree/security/oauth2/AuthProvider.java
> +    NONE,
ㅇㅇ 일단 혹시몰라서

2023-02-05 14:11 UTC, rt3310 commented on src/main/java/net/cafree/security/oauth2/OAuth2SuccessHandler.java
> +    public OAuth2SuccessHandler(JwtTokenProvider jwtTokenProvider) {
아 이건 잘못적은듯,,

2023-02-05 14:11 UTC, rt3310 commented on src/main/java/net/cafree/security/mapper/AttributeMapperFactory.java
> +            new EnumMap<AuthProvider, AttributeMappable>(AuthProvider.class);
1. Enum 타입으로 key를 제한할 수 있음
2. Array를 이용하기 때문에 성능적으로 우수
3. 해싱 과정이 필요 없어 HashMap보다 빠름

2023-02-05 14:11 UTC, rt3310 commented on src/main/java/net/cafree/security/SecurityConfig.java
>                                          .antMatchers("api/test/**")
음 바꿔야할듯

2023-02-05 22:53 UTC, lcomment commented
LGTM

2023-02-05 23:35 UTC, lcomment approved these changes

2023-02-05 23:36 UTC, merged